name: env3.6
channels:
- abinit
- matsci
- conda-forge
- defaults
dependencies:
- alabaster=0.7.10=py36_0
- appnope=0.1.0=py36_0
- ase=3.13.0=py36_1
- babel=2.3.4=py36_0
- bleach=1.5.0=py36_0
- ca-certificates=2017.1.23=0
- certifi=2017.1.23=py36_0
- coverage=4.0.3=py36_1
- curl=7.52.1=0
- cycler=0.10.0=py36_0
- decorator=4.0.11=py36_0
- docutils=0.13.1=py36_0
- entrypoints=0.2.2=py36_1
- freetype=2.7=1
- hdf4=4.2.12=0
- hdf5=1.8.17=9
- html5lib=0.999=py36_0
- icu=58.1=1
- imagesize=0.7.1=py36_0
- ipykernel=4.5.2=py36_0
- ipython=5.3.0=py36_0
- ipython_genutils=0.2.0=py36_0
- ipywidgets=6.0.0=py36_0
- jinja2=2.9.5=py36_0
- jpeg=9b=0
- jsonschema=2.5.1=py36_0
- jupyter=1.0.0=py36_0
- jupyter_client=5.0.0=py36_0
- jupyter_console=5.1.0=py36_0
- jupyter_core=4.3.0=py36_0
- jupyterlab=0.19.0=py36_0
- libgfortran=3.0.0=0
- libnetcdf=4.4.1.1=2
- libpng=1.6.28=0
- libsodium=1.0.10=0
- libtiff=4.0.6=7
- markupsafe=0.23=py36_1
- matplotlib=2.0.0=np112py36_3
- mistune=0.7.4=py36_0
- mongoengine=0.11.0=py36_0
- nbconvert=5.1.1=py36_1
- nbformat=4.2.0=py36_0
- ncurses=5.9=10
- netcdf4=1.2.7=np112py36_0
- networkx=1.11=py36_0
- nose=1.3.7=py36_2
- notebook=4.4.1=py36_0
- openssl=1.0.2h=3
- pandas=0.19.2=np112py36_1
- pandoc=1.19.2=0
- pandocfilters=1.4.1=py36_0
- patsy=0.4.1=py36_0
- pep8=1.7.0=py36_0
- pexpect=4.2.1=py36_0
- phonopy=1.11.8=np112py36_2
- pickleshare=0.7.3=py36_0
- pip=9.0.1=py36_0
- prompt_toolkit=1.0.14=py36_0
- ptyprocess=0.5.1=py36_0
- py=1.4.33=py36_0
- pygments=2.2.0=py36_0
- pyparsing=2.2.0=py36_0
- pyqt=4.11.4=py36_2
- pytest=3.0.7=py36_0
- python=3.6.1=0
- python-coveralls=2.9.0=py36_0
- python-dateutil=2.6.0=py36_0
- pytz=2016.10=py36_0
- pyyaml=3.12=py36_1
- pyzmq=16.0.2=py36_1
- qt=4.8.7=7
- qtconsole=4.3.0=py36_0
- readline=6.2=0
- requests=2.13.0=py36_0
- seaborn=0.7.1=py36_0
- setuptools=33.1.1=py36_0
- simplegeneric=0.8.1=py36_0
- sip=4.18=py36_1
- six=1.10.0=py36_1
- snowballstemmer=1.2.1=py36_0
- sphinx=1.5.4=py36_0
- sqlite=3.13.0=1
- statsmodels=0.8.0=np112py36_0
- terminado=0.6=py36_0
- testpath=0.3=py36_0
- tk=8.5.19=1
- tornado=4.4.2=py36_0
- traitlets=4.3.2=py36_0
- wcwidth=0.1.7=py36_0
- webencodings=0.5=py36_0
- wheel=0.29.0=py36_0
- widgetsnbextension=2.0.0=py36_0
- xz=5.2.2=0
- yaml=0.1.6=0
- zeromq=4.2.1=1
- zlib=1.2.11=0
- mkl=2017.0.1=0
- numpy=1.12.1=py36_0
- scipy=0.19.0=np112py36_0
- abipy 
- pip:
  - apscheduler==2.1.0
  - atomicfile==1.0
  - html2text==2016.9.19
  - ipython-genutils==0.2.0
  - jupyter-client==5.0.0
  - jupyter-console==5.1.0
  - jupyter-core==4.3.0
  - mock==2.0.0
  - mpmath==0.19
  - palettable==3.0.0
  - paramiko==2.1.2
  - pbr==2.1.0
  - periodic-table-plotter==0.2
  - pockets==0.3.2
  - prettytable==0.7.2
  - prompt-toolkit==1.0.14
  - pydispatcher==2.0.5
  - pytest-cov==2.4.0
  - scripttest==1.3
  - spglib==1.9.9.38
  - sphinxcontrib-napoleon==0.6.1
  - sphinxcontrib-programoutput==0.10
  - sympy==1.0
  - tabulate==0.7.7
  - tqdm==4.11.2
prefix: /Users/gmatteo/anaconda3/envs/env3.6

