language: python
python:
  - "2.7"
before_install:
  - sudo apt-get install -qq libhdf5-serial-dev hdf5-tools 
  - sudo apt-get install libnetcdf-dev
  - pip install -Iv https://bitbucket.org/jamesrhester/pycifrw/downloads/PyCifRW-3.6.1.tar.gz
  - pip install -Iv https://netcdf4-python.googlecode.com/files/netCDF4-1.0.2.tar.gz
  #- pip install netCDF4
  #- sudo apt-get update -qq
  #- sudo apt-get install -qq liblapack-dev 
  #- sudo apt-get install libzmq3-dev
  #- sudo apt-get install build-essential gfortran python-dev
  #python-nose python-numpy python-setuptools python-docutils \
  #python-h5py python-setuptools
  #- sudo apt-get install python-numpy 
  #- sudo apt-get install python-scipy 
  #- sudo apt-get install python-matplotlib 
  #- pip -q install numpy
  #- pip install scipy

# command to install dependencies
install: "pip install -r requirements.txt --use-mirrors"
# This is needed, otherwise, nosetests will import try to import wx.
before_script:
    - rm abipy/gui/__init__.py 
    - export LD_LIBRARY_PATH=/usr/lib/:$LD_LIBRARY_PATH
    - python -m netCDF4_utils
    #- abipy/dev_scripts/check_netcdf4.py
# command to run tests
script: nosetests
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - gmatteo@gmail.com
    on_success: change
    on_failure: always
