language: python
python:
  - "2.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq liblapack-dev 
  - sudo apt-get install -qq libhdf5-serial-dev hdf5-tools 
  - sudo apt-get install libnetcdf-dev
#  - sudo pip install numpy
#  - sudo pip install scipy
#  - sudo pip install -Iv https://bitbucket.org/jamesrhester/pycifrw/downloads/PyCifRW-3.6.1.tar.gz
#  - sudo pip install pymatgen
# command to install dependencies
install: "pip install -q -r requirements.txt --use-mirrors"
# command to run tests, e.g. python setup.py test
script: nosetests
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - gmatteo@gmail.com
    on_success: change
    on_failure: always
