#language: python

#os:
#  #- linux
#  - osx

matrix:
  include:
    #- os: linux
    #  python: 2.7
    #- os: linux
    #  python: 3.6
    - os: osx
      python: 2.7
      language: generic

#python: # We don't actually use the Travis Python, but this keeps it organized.
#  - "2.7"
#  - "3.4"
#  - "3.5"
#  - "3.6"

sudo: required

install:
  #- sudo apt-get update

  # Install conda https://conda.io/docs/travis.html
  - source conda_installer.sh

  # Add my channel
  - conda config --add channels gmatteo

  # See https://github.com/BVLC/caffe/issues/3884 and https://docs.continuum.io/mkl-optimizations/
  - conda install nomkl
  - conda install gcc scipy
  - conda install pandas
  - conda install netcdf4 
  # See hSttps://github.com/ContinuumIO/anaconda-issues/issues/1360
  - conda install hdf4=4.2.12
  - pip install pytest scripttest nose nose-exclude
  - pip install pep8 python-coveralls
  - conda install matplotlib seaborn
  - conda install ipython jupyter nbformat
  # Install abinit from gmatteo's conda channel.
  - conda install abinit
  # phonopy is not a requirement but we test scripts in data/runs that use it
  - conda install -c conda-forge phonopy
  # FIXME: I'm still using my fork
  - git clone https://github.com/gmatteo/pymatgen.git && cd pymatgen && pip install -q -r requirements.txt && pip install -q -r requirements-optional.txt && python setup.py install && cd ../
  - python setup.py install
  - mkdir -p ${HOME}/.abinit/abipy 
  - cp abipy/data/managers/travis_scheduler.yml ${HOME}/.abinit/abipy/scheduler.yml
  - cp abipy/data/managers/travis_manager.yml ${HOME}/.abinit/abipy/manager.yml
  - ./dev_scripts/pyclean.py .

# This is needed, otherwise, nosetests tries to import wx.
before_script:
    - rm abipy/gui/__init__.py 

# command to run tests
#script: abicheck.py; pytest -v abipy
script: abicheck.py; nosetests abipy -v --with-coverage --cover-package=abipy --logging-level=INFO
# This is to run the integration tests (slow)
#; pytest -v abipy/integration_tests

branches:
  only:
    - master
    - develop

after_success:
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
          coveralls;
  fi

notifications:
  email:
    recipients:
      - gmatteo@gmail.com
    on_success: change
    on_failure: always
